version: '3.8'

services:
  database:
    container_name: mysql-container
    image: mysql:latest
    restart: always
    ports:
      - "3306:3306"
    networks:
      - actions-deploy-network
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    env_file:
      - ./.env

  redis:
    container_name: redis-container
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    networks:
      - actions-deploy-network
    env_file:
      - ./.env

  app:
    container_name: actions-deploy-container
    image: ssolmoon/spring-actions-deploy:latest
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - database
      - redis
    networks:
      - actions-deploy-network
    env_file:
      - ./.env
    environment:
      - SPRING_PROFILES_ACTIVE=dev

networks:
  actions-deploy-network:
    driver: bridge

volumes:
  db_data:
    driver: local
